Repository Uninett/Argus, pull requests merged in 2022-10, with the labels that each got.

#481 Make DestinationConfig.is_deletable behave according to name
  src/argus/notificationprofile/media/base.py
  src/argus/notificationprofile/media/email.py
  src/argus/notificationprofile/views.py
Labels: notification, rc v1.8

#432 Add tests for filtering on open and stateful for api v1
  tests/incident/test_views.py
Labels: tests

#425 Let users know if one of their destinations is also in use by another user
  docs/api.rst
  src/argus/notificationprofile/media/base.py
  src/argus/notificationprofile/media/email.py
  src/argus/notificationprofile/media/sms_as_email.py
  src/argus/notificationprofile/serializers.py
  src/argus/notificationprofile/views.py
Labels: rr

#458 Validate tags before adding them to an incident
  src/argus/incident/models.py
  src/argus/incident/serializers.py
  src/argus/incident/views.py
Labels: rr

#413 Filter on duration of incidents
  CHANGELOG.md
  NOTES.md
  docs/api.rst
  src/argus/incident/V1/views.py
  src/argus/incident/filters.py
  src/argus/incident/models.py
  src/argus/incident/views.py
  tests/incident/test_filters.py
Labels: rc-future

#509 Remove unnecessary exists assertions in tests
  tests/notificationprofile/test_signals.py
  tests/notificationprofile/test_views.py
Labels: rr

#510 Ensure unique filter names in FilterFactory
  CHANGELOG.md
  src/argus/notificationprofile/factories.py
Labels: rr, rc-next

#456 Create change events on incident changes
  src/argus/incident/apps.py
  src/argus/incident/serializers.py
  src/argus/incident/signals.py
  src/argus/incident/views.py
  tests/incident/test_change_event.py
Labels: rc-future

#442 Add more tests for incident endpoints in API v1 & v2
  src/argus/incident/factories.py
  tests/incident/test_tags.py
  tests/incident/test_views.py
Labels: tests, rc-future

#515 Move import class from dotted path to utils
  src/argus/notificationprofile/media/__init__.py
  src/argus/util/utils.py
Labels: rr

#427 Add more tests for notificationprofile endpoints in API v1
  tests/notificationprofile/V1/test_views.py
Labels: tests

#518 Fix sending sms by accessing correct key
  CHANGELOG.md
  src/argus/notificationprofile/media/sms_as_email.py
Labels: bug, priority: high, rr
