Repository Uninett/Argus, pull requests merged in 2022-11, with the labels that each got.

#520 GitHub actions dependencies
  .github/workflows/python.yml
Labels: rr, rc-next

#483 Implement endpoints for bulk acknowledgements
  src/argus/incident/V1/urls.py
  src/argus/incident/serializers.py
  src/argus/incident/urls.py
  src/argus/incident/views.py
  tests/incident/test_views.py
Labels: enhancement, rc-next

#513 Except ValidationError when calling Tag.split()
  src/argus/incident/models.py
  src/argus/incident/serializers.py
  src/argus/incident/views.py
  tests/incident/test_views.py
Labels: rr

#523 Add test for updating of phone number in v1
  tests/auth/V1/test_views.py
Labels: rr

#424 Warn about impending expiry of source system API tokens
  CHANGELOG.md
  NOTES.md
  docs/development/management-commands.rst
  docs/integrating-monitoring-systems.rst
  src/argus/dev/management/commands/check_token_expiry.py
  src/argus/incident/apps.py
  src/argus/incident/filters.py
  src/argus/incident/models.py
  src/argus/incident/signals.py
  tests/incident/test_check_token_expiry.py
  tests/incident/test_filters.py
Labels: enhancement, auth, rc-future, rr

#466 Add new filter for notifications: event-type
  CHANGELOG.md
  NOTES.md
  docs/api.rst
  src/argus/notificationprofile/media/__init__.py
  src/argus/notificationprofile/models.py
  src/argus/notificationprofile/primitive_serializers.py
  tests/notificationprofile/test_models.py
Labels: rc-future, rr

#527 Add more docs about notification plugins
  docs/index.rst
  docs/notifications.rst
  docs/writing-plugins.rst
Labels: documentation, notification, API v2, rc v1.10, rr

#530 Fix sync_media()
  src/argus/notificationprofile/apps.py
  src/argus/notificationprofile/signals.py
Labels: rc v1.10

#449 Flatten json structure for posting acks
  CHANGELOG.md
  NOTES.md
  docs/api.rst
  src/argus/incident/V1/serializers.py
  src/argus/incident/V1/urls.py
  src/argus/incident/V1/views.py
  src/argus/incident/serializers.py
  src/argus/incident/views.py
  tests/incident/test_serializers.py
  tests/incident/test_views.py
Labels: rr

#516 Add base framework for ticket plugins
  CHANGELOG.md
  NOTES.md
  docs/api.rst
  docs/index.rst
  docs/site-specific-settings.rst
  docs/ticket-systems.rst
  docs/ticket-systems/settings.rst
  docs/ticket-systems/writing-ticket-system-plugins.rst
  src/argus/incident/serializers.py
  src/argus/incident/ticket/__init__.py
  src/argus/incident/ticket/base.py
  src/argus/incident/ticket/dummy.py
  src/argus/incident/urls.py
  src/argus/incident/views.py
  tests/incident/test_views.py
  tests/incident/ticket_plugins/__init__.py
  tests/incident/ticket_plugins/test_base.py
  tests/incident/ticket_plugins/test_dummy.py
Labels: rc v1.10

#538 Fix error handling for missing ticket settings
  src/argus/incident/ticket/base.py
Labels: rr

#543 Add init file to run auth v1 tests
  tests/auth/V1/__init__.py
Labels: rr
