Repository Uninett/Argus, pull requests merged in 2023-09, with the labels that each got.

#659 Remove filter string from filter model
  src/argus/notificationprofile/migrations/0013_remove_filter_filter_string.py
  src/argus/notificationprofile/models.py
Labels: rc-future

#683 Email plugin: Send one email per address
  src/argus/notificationprofile/media/email.py
Labels: notification

#697 Properly map notification destinations to events
  src/argus/notificationprofile/media/__init__.py
  tests/notificationprofile/test_media.py
Labels: bug
