Repository Uninett/Argus, pull requests merged in 2024-12, with the labels that each got.

#975 Remove unused local imports
  src/argus/auth/utils.py
  src/argus/filter/V1/serializers.py
  src/argus/incident/signals.py
  src/argus/incident/ticket/dummy.py
  src/argus/incident/views.py
  src/argus/notificationprofile/V1/serializers.py
  src/argus/notificationprofile/serializers.py
  src/argus/site/urls.py
Labels: lint/reformat

#974 Remove unused third party imports
  src/argus/dev/management/commands/list_filters.py
  src/argus/filter/V1/serializers.py
  src/argus/filter/apps.py
  src/argus/incident/signals.py
  src/argus/incident/views.py
  src/argus/notificationprofile/apps.py
  src/argus/notificationprofile/models.py
  src/argus/notificationprofile/signals.py
  src/argus/notificationprofile/urls.py
  src/argus/site/settings/test_CI.py
  src/argus/site/urls.py
  src/argus/site/utils.py
  src/argus/spa/urls.py
  src/argus/spa/utils.py
  tests/auth/test_spa_views.py
  tests/auth/test_views.py
Labels: lint/reformat

#1013 Reformat templates using djLint
  src/argus/base/templates/base.html
  src/argus/base/templates/index.html
  src/argus/incident/templates/incident/admin/fake_incident_add_form.html
  src/argus/incident/templates/incident/admin/incident_change_list.html
  src/argus/incident/templates/incident/admin/widgets/split_datetime_infinity.html
  src/argus/incident/templates/incident/ticket/default_ticket_body.html
  src/argus/notificationprofile/templates/notificationprofile/email.html
  src/argus/notificationprofile/templates/schemawrapper.html
Labels: lint/reformat

#1020 Allow filtering from columns
  changelog.d/+filterable-columns.added.md
  docs/development/howtos/htmx-frontend/customize-filtering.rst
  src/argus/htmx/incidents/customization.py
  src/argus/htmx/incidents/utils.py
  src/argus/htmx/templates/htmx/incidents/_incident_filterable_column.html
  src/argus/htmx/templates/htmx/incidents/_incident_filterbox.html
  src/argus/htmx/templates/htmx/incidents/_incident_table.html
  src/argus/htmx/templatetags/argus_htmx.py
  tests/htmx/test_incidents.py
Labels: frontend

#971 Return user to login page on unauthenticated HTMX request
  changelog.d/+unauthenticated-htmx-full-redirect.changed.md
  src/argus/htmx/middleware.py
Labels: frontend

#1029 ARGUS_HTMX_FILTER_FUNCTION can take a callable or a dotted function path
  changelog.d/1029.added.md
  docs/development/howtos/htmx-frontend/customize-filtering.rst
  src/argus/htmx/defaults.py
  src/argus/htmx/incidents/utils.py
  tests/htmx/incidents/__init__.py
  tests/htmx/incidents/test_utils.py
Labels: frontend

#1065 Fix incorrect width specifier in column filter input
  changelog.d/1065.fixed.md
  src/argus/htmx/templates/htmx/incidents/_incident_filterable_column.html
Labels: frontend

#1033 Keep column filters when autoreloading incident list
  changelog.d/1033.fixed.md
  src/argus/htmx/templates/htmx/incidents/_incident_table.html
Labels: frontend

#1028 Upgrade djLint version in pre-commit to 1.36.3
  .pre-commit-config.yaml
Labels: lint/reformat

#1031 Remove unused factory import from test
  tests/auth/test_spa_views.py
Labels: lint/reformat, cleanup

#1006 Add `F5` rules to ruff
  pyproject.toml
Labels: discussion, lint/reformat

#1018 Use double quotes in tags in templates
  src/argus/incident/templates/incident/admin/fake_incident_add_form.html
  src/argus/incident/templates/incident/admin/incident_change_list.html
Labels: lint/reformat

#1019 Use url pattern for internal links
  src/argus/incident/templates/incident/admin/incident_change_list.html
Labels: lint/reformat

#1007 Add `F6` rules to ruff
  pyproject.toml
Labels: lint/reformat

#1017 Add name to endblocks in templates
  src/argus/base/templates/base.html
  src/argus/incident/templates/incident/admin/fake_incident_add_form.html
  src/argus/incident/templates/incident/admin/incident_change_list.html
Labels: lint/reformat

#1011 Reorder/clean up imports in incident views
  src/argus/incident/views.py
Labels: lint/reformat

#1003 Ignore rules `F403`, `F405` star imports in ruff
  pyproject.toml
Labels: discussion, lint/reformat

#1005 Add `F4` rules to ruff
  pyproject.toml
Labels: discussion, lint/reformat

#1025 Drop name references for characters
  src/argus/incident/templates/incident/admin/fake_incident_add_form.html
Labels: lint/reformat

#1026 Add workflow to lint using djLint
  .github/workflows/python.yml
Labels: github actions, lint/reformat

#963 Add E4 rules to ruff
  pyproject.toml
Labels: discussion, lint/reformat

#1021 Auto close certain toast messages based on setting
  changelog.d/+auto-close-messages.changed.md
  docs/customization/htmx-frontend.rst
  src/argus/htmx/defaults.py
  src/argus/htmx/tailwindtheme/snippets/15-alert-message.css
  src/argus/htmx/templates/messages/_notification_message.html
  src/argus/htmx/templatetags/argus_htmx.py
Labels: frontend

#1027 Remove workflows from Argus-HTMX
  merge/.github/workflows/format.yml
  merge/.github/workflows/lint.yml
Labels: github actions, lint/reformat

#945 Install and set up django-rest-knox
  changelog.d/+add-knox-for-tokenauth.added.md
  pyproject.toml
  requirements-django42.txt
  requirements-django50.txt
  requirements-django51.txt
  requirements.txt
  src/argus/auth/authentication.py
  src/argus/auth/knox/__init__.py
  src/argus/auth/knox/urls.py
  src/argus/auth/knox/views.py
  src/argus/auth/serializers.py
  src/argus/auth/spa/__init__.py
  src/argus/auth/spa/serializers.py
  src/argus/auth/spa/urls.py
  src/argus/auth/spa/views.py
  src/argus/auth/urls.py
  src/argus/auth/views.py
  src/argus/site/api_v1_urls.py
  src/argus/site/api_v2_urls.py
  src/argus/site/settings/base.py
  tests/auth/test_auth.py
  tests/auth/test_knox_views.py
  tests/incident/test_source_system.py
Labels: priority: high, API v2, auth, geant

#1067 Remove unused imports from test_source_systems.py
  tests/incident/test_source_system.py
Labels: lint/reformat

#1068 Improve knox support
  src/argus/auth/knox/serializers.py
  src/argus/auth/knox/urls.py
  src/argus/auth/knox/views.py
  src/argus/auth/spa/views.py
  tests/auth/test_knox_views.py
Labels: documentation, API, tests, API v2, auth

#1070 Allow extending preferences page
  changelog.d/1070.added.md
  src/argus/htmx/templates/htmx/user/preferences.html
Labels: frontend

#1015 Systematize names: some easy pickings
  changelog.d/+singularize-easy-pickings.changed.md
  src/argus/htmx/incidents/customization.py
  src/argus/htmx/incidents/views.py
  src/argus/htmx/notificationprofile/__init__.py
  src/argus/htmx/notificationprofile/urls.py
  src/argus/htmx/templates/htmx/incidents/_incident_list_menubar.html
  src/argus/htmx/templates/htmx/incidents/_incident_list_refresh_info.html
  src/argus/htmx/templates/htmx/incidents/_incident_list_select_all_checkbox.html
  src/argus/htmx/templates/htmx/incidents/_incident_list_update_menu.html
  src/argus/htmx/templates/htmx/incidents/_incident_table.html
  src/argus/htmx/templates/htmx/incidents/incident_list.html
  src/argus/htmx/templates/htmx/incidents/responses/_incident_list_refresh.html
  src/argus/htmx/timeslot/__init__.py
  src/argus/htmx/timeslot/urls.py
  src/argus/htmx/urls.py
Labels: refactor, cleanup

#1082 Reduce number of queries to preferences db table
  changelog.d/1082.changed.md
  src/argus/auth/models.py
  src/argus/auth/utils.py
  src/argus/htmx/dateformat/views.py
  src/argus/htmx/incidents/views.py
  src/argus/htmx/themes/views.py
  src/argus/htmx/user/views.py
  tests/auth/test_models.py
Labels: frontend, performance

#964 Document how to vendor a repo
  changelog.d/+document-how-to-vendor-a-repo.added.md
  docs/development/howtos/vendor-a-repo.rst
Labels: documentation

#1012 Add `F8` rules to ruff
  pyproject.toml
Labels: lint/reformat

#1084 Make ruff more verbose
  .pre-commit-config.yaml
Labels: lint/reformat

#1022 Add loading indicator to form modals
  changelog.d/+bulk-action-indicator.added.md
  src/argus/htmx/templates/htmx/_base_form_modal.html
  src/argus/htmx/templates/htmx/incidents/_base_incident_update_modal.html
Labels: frontend

#1071 Keep django messages in queue on htmx redirects or refreshes
  changelog.d/1071.added.md
  src/argus/htmx/middleware.py
  tests/htmx/test_middleware.py
Labels: frontend

#1089 Declare color scheme for the "argus"-theme
  changelog.d/1088.changed.md
  changelog.d/1088.fixed.md
  docs/customization/htmx-frontend.rst
  src/argus/htmx/defaults.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/tailwindtheme/tailwind.config.js
Labels: frontend

#1087 Add rudimentary timeslot support
  changelog.d/+add-rudimentary-timeslots-page.added.md
  src/argus/htmx/templates/htmx/base.html
  src/argus/htmx/templates/htmx/timeslot/_timeslot_detail.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_confirm_delete.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_detail.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_form.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_list.html
  src/argus/htmx/timeslot/urls.py
  src/argus/htmx/timeslot/views.py
Labels: frontend

#1091 Use default rules for ruff
  pyproject.toml
Labels: lint/reformat

#1095 Add rudimentary notificationprofile support
  changelog.d/+add-rudimentary-notificationprofiles-page.added.md
  src/argus/htmx/notificationprofile/urls.py
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/base.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_detail.html
  src/argus/htmx/templates/htmx/notificationprofile/notificationprofile_confirm_delete.html
  src/argus/htmx/templates/htmx/notificationprofile/notificationprofile_detail.html
  src/argus/htmx/templates/htmx/notificationprofile/notificationprofile_form.html
  src/argus/htmx/templates/htmx/notificationprofile/notificationprofile_list.html
Labels: frontend

#1097 Improve dropdown widget
  changelog.d/+improve-dropdown-widget.changed.md
  src/argus/htmx/incidents/filter.py
  src/argus/htmx/templates/htmx/forms/dropdown_select_multiple.html
  src/argus/htmx/templates/htmx/incidents/widgets/incident_source_select.html
  src/argus/htmx/widgets.py
Labels: frontend, polish, CSS
