Repository Uninett/Argus, pull requests merged in 2024-11, with the labels that each got.

#932 Upgrade ruff in pre-commit to 0.7.2
  .pre-commit-config.yaml
Labels: dependencies

#889 Add model to hold user preferences
  changelog.d/+user-prefderences.added.md
  docs/development/howtos/add-more-preferences.rst
  src/argus/auth/admin.py
  src/argus/auth/context_processors.py
  src/argus/auth/migrations/0004_add_preferences_model.py
  src/argus/auth/models.py
  src/argus/auth/utils.py
  tests/auth/models.py
  tests/auth/test_models.py
Labels: enhancement, frontend, data model, admin, user administration

#943 Robustify preferences lookup
  src/argus/auth/models.py
  tests/auth/test_models.py
Labels: bug

#937 Return success only on changed preference
  src/argus/auth/utils.py
Labels: bug

#934 Document how to fix a broken migration
  changelog.d/+docs-how-to-fix-migration.added.md
  docs/development/howtos/recover-from-migration-trouble.rst
Labels: documentation

#960 Clean up ruff pre-commit
  .pre-commit-config.yaml
Labels: linting

#965 Check for membership with `a not in b`
  src/argus/incident/serializers.py
  src/argus/notificationprofile/V1/serializers.py
Labels: linting

#953 Only check formatting of changed files with ruff
  .github/workflows/format.yml
Labels: linting

#966 Use `is`/`is not` to compare with `None`
  src/argus/notificationprofile/V1/serializers.py
  src/argus/site/settings/__init__.py
Labels: linting

#968 Rewrite assigned lambda expression as def
  tests/auth/test_auth.py
Labels: linting

#967 Use `isinstance` for checking that settings are dict
  src/argus/notificationprofile/serializers.py
Labels: linting

#961 Split up import of multiple modules on one line
  src/argus/incident/factories.py
Labels: linting

#973 Remove unused stdlib imports
  src/argus/dev/management/commands/create_fake_incident.py
  src/argus/filter/V1/serializers.py
  src/argus/filter/filterwrapper.py
  src/argus/incident/serializers.py
  src/argus/notificationprofile/media/__init__.py
  src/argus/notificationprofile/media/base.py
  src/argus/notificationprofile/media/email.py
  src/argus/notificationprofile/media/sms_as_email.py
  src/argus/notificationprofile/models.py
  src/argus/notificationprofile/views.py
  src/argus/site/settings/dev.py
Labels: linting

#972 Remove unused imports from tests
  tests/auth/test_models.py
  tests/dev/test_check_token_expiry.py
  tests/incident/test_filters.py
  tests/notificationprofile/test_github236.py
  tests/site/test_settings_helpers.py
Labels: linting

#947 Add link to frontend docs to README
  README.md
Labels: documentation, blocked
