Repository Uninett/Argus, pull requests merged in 2024-04, with the labels that each got.

#738 Fix typo in admin that prevents sorting on incident id
  changelog.d/+fix-admin-typo.fixed.md
  src/argus/incident/admin.py
Labels: admin

#742 Bump cryptography from 42.0.2 to 42.0.5
  requirements-django32.txt
  requirements-django42.txt
  requirements-django50.txt
  requirements.txt
Labels: dependencies

#745 Use keep a changelog categories for towncrier
  README.md
  pyproject.toml
Labels: documentation

#746 Change references to Django docs to version 4.2
  README.md
  changelog.d/746.fixed.md
  src/argus/incident/templates/incident/admin/widgets/split_datetime_infinity.html
  src/argus/incident/ticket/dummy.py
  src/argus/site/settings/base.py
  src/argus/site/urls.py
  src/argus/site/wsgi.py
  src/argus/util/admin_utils.py
  src/argus/util/datetime_utils.py
  tests/incident/test_source_system.py
Labels: documentation

#753 Do not allow deletion of used destinations
  changelog.d/753.fixed.md
  src/argus/notificationprofile/media/base.py
  src/argus/notificationprofile/media/email.py
  src/argus/notificationprofile/media/sms_as_email.py
  tests/notificationprofile/destinations/test_sms.py
Labels: bug

#763 Add docs for toggle_profile_activation command
  docs/development/management-commands.rst
Labels: documentation

#771 Add admin actions to change profile activation in bulk
  changelog.d/748.added.md
  src/argus/notificationprofile/admin.py
Labels: admin

#760 Debug notification sending
  changelog.d/+debug-notification-sending-1.changed.md
  changelog.d/+debug-notification-sending-2.changed.md
  src/argus/notificationprofile/media/__init__.py
  src/argus/notificationprofile/media/base.py
  src/argus/notificationprofile/media/email.py
  src/argus/notificationprofile/media/sms_as_email.py
  src/argus/notificationprofile/models.py
Labels: notification, debug

#773 Make dev tests run
  tests/dev/__init__.py
Labels: tests

#762 Update release checklist
  changelog.d/+update-release-checklist.changed.md
  docs/development.rst
  docs/development/howtos.rst
  docs/development/howtos/release-checklist.rst
  docs/development/release-checklist.rst
Labels: documentation

#798 Link two first columns in Incident admin
  changelog.d/+fix-incident-admin-list-link.changed.md
  src/argus/incident/admin.py
Labels: admin

#765 Add howto for testing the notifications subsystem
  changelog.d/+howto-notification-testing.added.md
  docs/development.rst
  docs/development/howtos/notification-system-testing.rst
  docs/development/notes.rst
Labels: documentation

#797 Fix internal server error in timeslot admin due to removed method
  changelog.d/797.fixed.md
  src/argus/notificationprofile/models.py
Labels: bug, admin

#800 Add date drilldown to incident list in admin
  changelog.d/739.added.md
  src/argus/incident/admin.py
Labels: admin
