Repository Uninett/Argus, pull requests merged in 2024-08, with the labels that each got.

#852 Make description editable
  changelog.d/811.changed.md
  src/argus/incident/serializers.py
  tests/incident/test_change_event.py
  tests/incident/test_views.py
Labels: API

#814 Make git ignore all dotfiles by default
  .gitignore
Labels: after-demo

#864 Minor documentation fixups
  README.md
  changelog.d/broken-dataporten-link.fixed.txt
  changelog.d/update-readme-command-naming.fixed.txt
  docs/models.rst
Labels: documentation

#863 Replace STATICFILES_STORAGE with STORAGES
  changelog.d/+set-storages.changed.md
  src/argus/site/settings/base.py
  src/argus/site/settings/dev.py
  src/argus/site/settings/prod.py
  src/argus/site/settings/test_CI.py
Labels: Django
