Repository Uninett/Argus, pull requests merged in 2024-07, with the labels that each got.

#835 Force override ZIP files from artifacts
  .github/workflows/publish-test-results.yml
Labels: tests

#837 Prefetch related data in incidents endpoint
  changelog.d/837.fixed.md
  src/argus/incident/views.py
Labels: optimization

#847 Move filtered_incidents to argus.filter
  changelog.d/+move-filtered-incidents2.changed.md
  src/argus/dev/management/commands/bulk_incidents.py
  src/argus/filter/filters.py
  src/argus/filter/filterwrapper.py
  src/argus/filter/queryset_filters.py
  src/argus/notificationprofile/V1/views.py
  src/argus/notificationprofile/media/__init__.py
  src/argus/notificationprofile/models.py
  src/argus/notificationprofile/views.py
  tests/dev/test_bulk_incidents.py
  tests/filter/test_filterwrapper.py
  tests/filter/test_models.py
  tests/filter/test_queryset_filters.py
  tests/incident/test_views.py
  tests/notificationprofile/V1/test_views.py
  tests/notificationprofile/test_views.py
Labels: demo

#850 Extend (OVERRIDING|EXTRA)_APPS to support middleware
  changelog.d/+extra-middleware.added.md
  src/argus/site/settings/_serializers.py
  src/argus/site/settings/base.py
  src/argus/site/utils.py
Labels: demo

#848 Make filter backends pluginable
  changelog.d/+plugin-filter.added.md
  docs/development/howtos/customizing-filtering.rst
  src/argus/dev/management/commands/bulk_incidents.py
  src/argus/dev/management/commands/list_filters.py
  src/argus/filter/__init__.py
  src/argus/filter/checks.py
  src/argus/filter/default.py
  src/argus/filter/filters.py
  src/argus/filter/filterwrapper.py
  src/argus/filter/queryset_filters.py
  src/argus/filter/serializers.py
  src/argus/filter/validators.py
  src/argus/incident/views.py
  src/argus/notificationprofile/checks.py
  src/argus/notificationprofile/media/__init__.py
  src/argus/notificationprofile/models.py
  src/argus/notificationprofile/serializers.py
  src/argus/notificationprofile/views.py
  tests/filter/dummyplugin.py
  tests/filter/test_filterplugin.py
Labels: notification, filter, new setting, demo
