Repository Uninett/Argus, pull requests merged in 2024-10, with the labels that each got.

#881 Convert Django's ValidationError to drf
  changelog.d/+convert-exceptions.changed.md
  src/argus/drf/__init__.py
  src/argus/site/settings/base.py
Labels: API, unexpected 50x

#886 Use get_user_model() to import correct User-model
  src/argus/auth/management/commands/grantsuperuser.py
  src/argus/auth/management/commands/revokesuperuser.py
  src/argus/auth/management/commands/setpassword.py
  src/argus/dev/management/commands/bulk_incidents.py
  src/argus/dev/management/commands/initial_setup.py
  src/argus/incident/admin.py
  src/argus/incident/forms.py
  src/argus/incident/models.py
  src/argus/incident/serializers.py
  src/argus/incident/views.py
  src/argus/notificationprofile/media/base.py
  src/argus/notificationprofile/media/email.py
  src/argus/notificationprofile/media/sms_as_email.py
  src/argus/notificationprofile/models.py
  src/argus/notificationprofile/signals.py
  tests/auth/test_auth.py
  tests/dev/test_initial_setup.py
  tests/incident/test_source_system.py
Labels: refactor

#887 Generate factory source users with a counter
  src/argus/auth/factories.py
Labels: tests

#888 Replace level constants with Level Django enum
  src/argus/dev/management/commands/create_fake_incident.py
  src/argus/filter/V1/serializers.py
  src/argus/filter/filters.py
  src/argus/filter/swappable/serializers.py
  src/argus/incident/V1/views.py
  src/argus/incident/constants.py
  src/argus/incident/factories.py
  src/argus/incident/forms.py
  src/argus/incident/models.py
  src/argus/notificationprofile/serializers.py
  tests/filter/test_filterwrapper.py
Labels: refactor

#883 Improve reference documentation
  changelog.d/+docs-reference-section.changed.md
  docs/index.rst
  docs/models.rst
  docs/reference.rst
  docs/reference/api.rst
  docs/reference/glossary.rst
  docs/reference/img/ER_model.png
  docs/reference/models.rst
  docs/reference/site-specific-settings.rst
Labels: documentation, refactor

#882 Improve docs about integrations
  docs/integrations/_note.rst
  docs/integrations/glue-services/index.rst
  docs/integrations/notifications/email-plugin.rst
  docs/integrations/notifications/index.rst
  docs/integrations/notifications/sms-plugin.rst
  docs/integrations/ticket-systems/index.rst
Labels: documentation, refactor

#892 Improve authentication docs
  docs/index.rst
  docs/reference/authentication.rst
  docs/reference/site-specific-settings.rst
Labels: documentation, refactor

#893 Add howto for regenerating ER diagram
  docs/development/howtos/regenerate-the-ER-diagram.rst
Labels: documentation

#885 Ensure all templates and static files are replaceable
  changelog.d/+replacable-base-template.changed.md
  src/argus/base/__init__.py
  src/argus/base/apps.py
  src/argus/base/static/favicon.svg
  src/argus/base/templates/base.html
  src/argus/base/templates/index.html
  src/argus/site/settings/base.py
Labels: refactor, geant

#895 Document (OVERRIDING|EXTRA)_APPS middleware setting
  changelog.d/+middleware-app-setting-docs.changed.md
  docs/reference/site-specific-settings.rst
Labels: documentation

#894 Add new section about customization
  changelog.d/+add-customization-section.added.md
  docs/customization/index.rst
  docs/development/howtos/customizing-filtering.rst
  docs/index.rst
  docs/integrations/index.rst
  docs/reference/authentication.rst
Labels: documentation

#897 Fix some openapi warnings
  changelog.d/+fix-some-openapi-warnings.changed.md
  src/argus/auth/serializers.py
  src/argus/auth/urls.py
  src/argus/auth/views.py
  src/argus/incident/V1/serializers.py
  src/argus/incident/V1/views.py
  src/argus/incident/serializers.py
  src/argus/incident/views.py
  src/argus/notificationprofile/views.py
  src/argus/site/serializers.py
  src/argus/site/views.py
  tests/incident/test_serializers.py
Labels: documentation, API, API v2, refactor

#898 Clean up OAuth2 helper functions
  changelog.d/+oauth2.removed.md
  src/argus/auth/utils.py
  tests/auth/test_utils.py
Labels: priority: high, blocked, auth, new setting

#917 Use pipx to install towncrier
  .github/workflows/towncrier.yml
Labels: bug

#907 Give React SPA frontend specific things a home
  changelog.d/+spa-frontend-specific.changed.md
  codecov.yml
  docs/development/howtos/federated-logins.rst
  docs/reference/react-frontend.rst
  docs/reference/site-specific-settings.rst
  src/argus/auth/V1/urls.py
  src/argus/auth/serializers.py
  src/argus/auth/urls.py
  src/argus/auth/utils.py
  src/argus/auth/views.py
  src/argus/dataporten/views.py
  src/argus/site/settings/backend.py
  src/argus/site/settings/base.py
  src/argus/site/settings/dev.py
  src/argus/site/settings/dockerdev.py
  src/argus/site/settings/prod.py
  src/argus/site/settings/test_CI.py
  src/argus/site/urls.py
  src/argus/spa/__init__.py
  src/argus/spa/dataporten/__init__.py
  src/argus/spa/dataporten/social.py
  src/argus/spa/settings.py
  src/argus/spa/spa_settings.py
  src/argus/spa/spa_urls.py
  src/argus/spa/urls.py
  src/argus/spa/utils.py
  src/argus/spa/views.py
  tests/auth/__init__.py
  tests/auth/test_auth.py
  tests/auth/test_views.py
  tests/spa/__init_.py
  tests/spa/test_utils.py
  tests/spa/test_views.py
Labels: help wanted, frontend, API, API v2, auth

#906 Improve app settings
  changelog.d/+improve-app-settings.changed.md
  docs/reference/site-specific-settings.rst
  src/argus/site/settings/_serializers.py
  src/argus/site/settings/base.py
  src/argus/site/urls.py
  src/argus/site/utils.py
  tests/site/test_settings_helpers.py
Labels: documentation, enhancement, geant

#899 Add easy way to include htmx frontend
  changelog.d/+frontend-switch.added.md
  docs/development/howtos/federated-logins.rst
  docs/reference/htmx-frontend.rst
  pyproject.toml
  src/argus/htmx/__init__.py
  src/argus/htmx/htmx_urls.py
  src/argus/htmx/settings.py
  src/argus/htmx/urls.py
  src/argus/site/settings/__init__.py
  src/argus/site/settings/base.py
  src/argus/site/urls.py
Labels: enhancement, frontend, priority: high, dependencies, auth, HTMx

#918 Use ruff Github action for critical linting
  .github/workflows/python.yml
  pyproject.toml
Labels: refactor

#926 Update and fix federated login docs
  docs/development/howtos/federated-logins.rst
Labels: documentation, blocked
