Repository Uninett/Argus, pull requests merged in 2024-09, with the labels that each got.

#854 Fix openapi parameters for incidents/ and incidents/mine
  changelog.d/+fix-open-api-parameters.fixed.md
  src/argus/filter/filters.py
  src/argus/incident/views.py
Labels: documentation

#873 Add old level as parameter to create level ChangeEvents
  src/argus/incident/models.py
Labels: bug

#880 Remove FilterBlobSerializer dependents from plugin
  changelog.d/+simplify-filter-plugin.changed.md
  src/argus/dev/management/commands/list_filters.py
  src/argus/filter/checks.py
  src/argus/filter/default.py
  src/argus/filter/serializers.py
  src/argus/filter/swappable/__init__.py
  src/argus/filter/swappable/serializers.py
  src/argus/filter/validators.py
  src/argus/notificationprofile/checks.py
  src/argus/notificationprofile/serializers.py
  src/argus/notificationprofile/views.py
Labels: filter, refactor, geant
