Repository Uninett/Argus, pull requests merged in 2025-04, with the labels that each got.

#1326 Mark up the sections in details page with drop shadows
  changelog.d/+cardify-details-page.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend

#1322 Test on Python 3.13
  .github/workflows/python.yml
  changelog.d/+python313.changed.md
  constraints.txt
  requirements-django42.txt
  requirements-django50.txt
  requirements-django51.txt
  requirements.txt
  tox.ini
Labels: dependencies

#1318 Pagination improvements
  changelog.d/+pagination-improvements.changed.md
  src/argus/htmx/incident/views.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/_incident_table.html
  src/argus/htmx/templates/htmx/incident/_incident_table_paginator.html
  src/argus/htmx/templates/htmx/incident/_incident_table_paginator_pageitem.html
Labels: frontend

#1233 Death to autocomplete
  changelog.d/+death-to-autocomplete.changed.md
  docs/development/howtos/htmx-frontend/custom-incident-actions.rst
  src/argus/htmx/templates/django/forms/widgets/attrs.html
  src/argus/htmx/templates/htmx/incident/_incident_list_menubar.html
  src/argus/htmx/templates/htmx/user/_dateformat_dropdown.html
  src/argus/htmx/templates/htmx/user/_page_size_dropdown.html
  src/argus/htmx/templates/htmx/user/_theme_dropdown.html
  src/argus/htmx/templates/htmx/user/_update_interval_dropdown.html
Labels: frontend

#1337 Fix days selector bug where first option is toggled on input click
  changelog.d/1335.fixed.md
  src/argus/htmx/templates/htmx/timeslot/timerecurrence_div.html
Labels: bug, frontend

#1333 Improve wee things in details page
  changelog.d/+improve-event-list.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend

#1334 Programmatically connect labels to inputs
  changelog.d/1332.fixed.md
  src/argus/htmx/destination/views.py
  src/argus/htmx/templates/htmx/forms/input_field.html
Labels: frontend, accessibility

#1331 Improve profiles forms UX
  changelog.d/1312.changed.md
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/forms/input_field.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_buttons.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_form.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_form_div.html
  src/argus/htmx/templates/htmx/notificationprofile/notificationprofile_list.html
Labels: frontend

#1345 Add admin link to user menu dropdown
  changelog.d/1261.added.md
  src/argus/htmx/templates/htmx/user/_user_menu.html
Labels: frontend

#1349 Make feed sections max height conform to the max height of details section
  changelog.d/1327.fixed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend

#1348 Group user preferences in user menu dropdown
  changelog.d/1256.changed.md
  src/argus/htmx/templates/htmx/user/_user_menu.html
  src/argus/htmx/templates/htmx/user/_user_menu_preferences.html
  src/argus/htmx/templates/htmx/user/_user_menu_user_preferences.html
Labels: frontend

#1132 Make the profiles delete button a modal
  src/argus/htmx/modals.py
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/_base_form_modal_experimental.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_buttons.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_form.html
Labels: help wanted, nonews

#1351 Set italic using em tag instead of CSS
  changelog.d/1343.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/_base_confirm_dialog.html
  src/argus/htmx/templates/htmx/forms/dropdown_select_multiple.html
  src/argus/htmx/templates/htmx/forms/input_field.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_form_div.html
  src/argus/htmx/templates/htmx/timeslot/timerecurrence_div.html
Labels: frontend, accessibility

#1347 Add divider before logout in user menu dropdown
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/user/_user_menu.html
Labels: frontend, nonews

#1358 Make delete modal
  changelog.d/+make-delete-modal.changed.md
  src/argus/htmx/modals.py
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/templates/htmx/_base_form_modal_experimental.html
  src/argus/htmx/templates/htmx/timeslot/_timeslot_form.html
  src/argus/htmx/timeslot/views.py
Labels: frontend, consistency

#1366 Fix days field by simplifying
  changelog.d/+simplify-days-field.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/timeslot/checkbox_option.html
  src/argus/htmx/timeslot/views.py
Labels: bug, frontend

#1370 Stop saving invalid form data in modal forms
  changelog.d/+dont-erase-url-on-invalid-ticket-form.fixed.md
  src/argus/htmx/incident/views.py
Labels: frontend

#1377 Use `gap` instead of `px` between severity levels in range selector
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/_incident_filterbox.html
Labels: frontend, polish, nonews

#1372 Allow saving empty ticket URL again
  changelog.d/1371.fixed.md
  src/argus/htmx/templates/htmx/incident/_incident_ticket_manual_create_modal.html
Labels: bug, frontend, priority: high

#1378 Use neutral-content as temporary fix for table separator contrast problems
  changelog.d/1378.fixed.md
  src/argus/htmx/templates/htmx/incident/_incident_table_cell_wrapper_default.html
  src/argus/htmx/templates/htmx/incident/_incident_table_cell_wrapper_link_to_details.html
Labels: frontend

#1375 Use neutral-content as temporary fix for tag badges contrast problems
  changelog.d/1375.fixed.md
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend

#1380 Allow limiting shown incidents by age
  changelog.d/+timeframes.added.md
  src/argus/htmx/constants.py
  src/argus/htmx/incident/constants.py
  src/argus/htmx/incident/forms.py
  src/argus/htmx/incident/views.py
  src/argus/htmx/templates/htmx/incident/_incident_list_refresh_info.html
Labels: frontend

#1387 Center header text on incident details page
  changelog.d/1298.fixed.md
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend, polish

#1388 Make incident duration more human readable
  changelog.d/1196.fixed.md
  src/argus/htmx/incident/views.py
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend, polish

#1363 Make table footer styles more blended in
  changelog.d/1363.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/_incident_list_refresh_info.html
  src/argus/htmx/templates/htmx/incident/_incident_table.html
  src/argus/htmx/templates/htmx/incident/_incident_table_paginator.html
  src/argus/htmx/templates/htmx/incident/_incident_table_paginator_pageitem.html
Labels: frontend, polish, ddn

#1392 Add documentation about Font Awesome icon pack
  docs/development/howtos/htmx-frontend/font_awesome.rst
Labels: documentation, nonews

#1390 Convert filterable column unicode search icon to fontawesome
  changelog.d/1390.added.md
  src/argus/htmx/templates/htmx/incident/cells/_incident_filterable_column_header.html
Labels: frontend, blocked

#1393 Tweak select dropdowns in incident list table footer
  changelog.d/1393.changed.md
  src/argus/htmx/templates/htmx/incident/_incident_list_refresh_info.html
Labels: frontend, polish

#1395 Use simple email defaults in base, tls in prod
  changelog.d/1395.changed.md
  src/argus/site/settings/base.py
  src/argus/site/settings/prod.py
Labels: change setting

#1404 Catch ticket system trouble in frontend
  changelog.d/+htmx-catch-ticket-exception.changed.md
  src/argus/htmx/incident/views.py
Labels: enhancement
