Repository Uninett/Argus, pull requests merged in 2025-03, with the labels that each got.

#1187 Add a pull request template
  .github/pull_request_template.md
Labels: DevEx, nonews

#1193 Move channels-app and CORS settings to spa
  changelog.d/+fix-spa-deps.fixed.md
  docs/reference/react-frontend.rst
  src/argus/site/settings/base.py
  src/argus/spa/settings.py
  src/argus/spa/spa_settings.py
Labels: frontend, change setting

#1179 Use <time>-tag for incident datetimes
  src/argus/htmx/incident/views.py
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend, nonews

#1114 Filter incident by tags using simple input field
  changelog.d/1044.added.md
  src/argus/htmx/incident/filter.py
  src/argus/htmx/templates/htmx/incident/_incident_filterbox.html
Labels: enhancement, frontend, HTMx

#1212 Add documentation on how to customize incident actions
  changelog.d/1212.added.md
  docs/development/howtos/htmx-frontend/custom-incident-actions.rst
  docs/development/howtos/htmx-frontend/override_templates.rst
Labels: documentation

#1090 Set default opacity in loading overlay to 50%
  changelog.d/+configurable-opacity-in-loading-box.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/tailwindtheme/snippets/20-loading-box.css
Labels: polish

#1203 Add support to new frontend for autocreating tickets
  changelog.d/1202.added.md
  src/argus/htmx/incident/views.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/_incident_ticket_edit_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_ticket_manual_create_modal.html
  src/argus/htmx/templates/htmx/incident/incident_detail.html
  src/argus/htmx/utils.py
  src/argus/incident/ticket/base.py
  src/argus/incident/ticket/utils.py
  src/argus/incident/views.py
  tests/incident/ticket_plugins/test_utils.py
Labels: frontend, ticket system

#1141 Polish timeslots page: easy pickings
  src/argus/htmx/templates/htmx/timeslot/_timeslot_form.html
  src/argus/htmx/templates/htmx/timeslot/base.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_detail.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_form.html
  src/argus/htmx/templates/htmx/timeslot/timeslot_list.html
  src/argus/htmx/timeslot/views.py
Labels: frontend, polish, nonews

#1215 Explain why ARGUS_FRONTEND_URL is needed better
  docs/reference/htmx-frontend.rst
  docs/reference/react-frontend.rst
Labels: documentation, nonews

#1234 Add troubleshooting guide
  changelog.d/+add-troubleshooting-guide.added.md
  docs/development.rst
  docs/development/troubleshooting.rst
Labels: documentation

#1235 Improve niggling syntax problems in the docs
  docs/customization.rst
  docs/index.rst
  docs/reference/admin.rst
  docs/reference/api.rst
  docs/reference/react-frontend.rst
Labels: documentation, nonews

#1219 Move navbar notification links to user menu
  changelog.d/+move-header-nav-items.changed.md
  src/argus/htmx/templates/htmx/base.html
  src/argus/htmx/templates/htmx/user/_user_menu.html
  src/argus/htmx/templates/htmx/user/_user_menu_destinations.html
  src/argus/htmx/templates/htmx/user/_user_menu_notification_config.html
Labels: frontend, refactor

#1241 Make column for showing status as color fill
  changelog.d/+color-status-column.added.md
  docs/customization/htmx-frontend.rst
  src/argus/htmx/defaults.py
  src/argus/htmx/incident/customization.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/_incident_table.html
  src/argus/htmx/templates/htmx/incident/_incident_table_cell.html
  src/argus/htmx/templates/htmx/incident/_incident_table_row.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_color_status.html
Labels: frontend

#1258 Fix badge colors
  changelog.d/+fix-badge-colors.changed.md
  src/argus/htmx/templates/htmx/incident/cells/_incident_level.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_status.html
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: frontend

#1248 Add tests for `htmx/incident/customization.py`
  tests/htmx/incident/test_customization.py
Labels: nonews

#1267 Fix bug where update modal is shown om filter delete action
  changelog.d/1266.fixed.md
  src/argus/htmx/incident/views.py
Labels: bug, frontend

#1236 Allow removing timerecurrences from a timeslot
  changelog.d/+delete-timerecurrences.added.md
  src/argus/htmx/timeslot/views.py
Labels: frontend, notification

#1284 Add borders between table rows
  changelog.d/1253.added.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/_incident_table_cell.html
  src/argus/htmx/templates/htmx/incident/_incident_table_row.html
Labels: frontend

#1282 Use accent color a lot less
  changelog.d/+use-less-accent-color.changed.md
  src/argus/htmx/incident/filter.py
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/forms/dropdown_select_multiple.html
  src/argus/htmx/templates/htmx/incident/_incident_filterbox.html
  src/argus/htmx/templates/htmx/incident/_incident_list_update_menu.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_checkbox.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_filterable_column_header.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_list_select_all_checkbox_header.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_ticket.html
  src/argus/htmx/templates/registration/login.html
Labels: frontend

#1217 Deprecate api v1
  changelog.d/+deprecate-api-v1.changed.md
  docs/reference/api.rst
  src/argus/auth/V1/urls.py
  src/argus/auth/V1/views.py
  src/argus/incident/V1/urls.py
  src/argus/incident/V1/views.py
  src/argus/notificationprofile/V1/urls.py
  src/argus/notificationprofile/V1/views.py
  src/argus/site/api_v1_urls.py
  src/argus/site/urls.py
  src/argus/site/views.py
Labels: API

#1281 Make table cells clickable
  changelog.d/+clickable-teable-cells.changed.md
  docs/customization/htmx-frontend.rst
  src/argus/htmx/incident/customization.py
  src/argus/htmx/templates/htmx/incident/_incident_table_cell_wrapper_default.html
  src/argus/htmx/templates/htmx/incident/_incident_table_cell_wrapper_link_to_details.html
Labels: frontend

#1162 Convert uncaught exceptions to messages.error
  changelog.d/+convert-exceptions-to-messages.changed.md
  src/argus/htmx/middleware.py
Labels: frontend, error handling

#1309 Update README with warnings of deprecations
  README.md
Labels: frontend, priority: high, API, dependencies, API v2, Django, nonews

#1311 Make basic inputs in forms use a universal design
  changelog.d/1311.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/destination/_collapse_with_forms.html
  src/argus/htmx/templates/htmx/destination/_create_form.html
  src/argus/htmx/templates/htmx/destination/_edit_form.html
  src/argus/htmx/templates/htmx/forms/input_field.html
  src/argus/htmx/templates/htmx/incident/_filter_create_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_acknowledge_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_close_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_reopen_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_ticket_edit_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_ticket_manual_create_modal.html
  src/argus/htmx/templates/htmx/timeslot/_timeslot_form.html
  src/argus/htmx/templates/htmx/timeslot/timerecurrence_div.html
Labels: frontend, priority: high

#1313 Add tests for `argus/htmx/incident/filter.py`
  tests/htmx/incident/test_filter.py
Labels: nonews

#1308 Show absolute details_url in frontend details page
  changelog.d/+fix-details-url-in-details-page.changed.md
  src/argus/htmx/templates/htmx/incident/incident_detail.html
  src/argus/incident/models.py
Labels: bug, frontend, ddn

#1314 Fix badges on details page
  changelog.d/1244.fixed.md
  changelog.d/1314.changed.md
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: bug, frontend
