Repository Uninett/Argus, pull requests merged in 2025-02, with the labels that each got.

#1175 Move websockets-stuff to spa-dir
  README.md
  changelog.d/+move-ws.changed.md
  docs/django_settings.py
  docs/reference/react-frontend.rst
  docs/reference/site-specific-settings.rst
  pyproject.toml
  requirements-django42.txt
  requirements-django50.txt
  requirements-django51.txt
  requirements.txt
  requirements/htmx.txt
  src/argus/site/settings/base.py
  src/argus/spa/apps.py
  src/argus/spa/settings.py
  src/argus/spa/spa_settings.py
  src/argus/spa/ws/__init__.py
  src/argus/spa/ws/asgi.py
  src/argus/spa/ws/consumers.py
  src/argus/spa/ws/models.py
  src/argus/ws/__init__.py
  tox.ini
Labels: change setting

#1171 Add MAINTAINING.rst
  MAINTAINING.rst
  README.md
  changelog.d/+add-maintaining-file.added.md
Labels: documentation

#1181 Allow customizing user menu
  src/argus/htmx/templates/htmx/base.html
  src/argus/htmx/templates/htmx/user/_user_menu.html
  src/argus/htmx/templates/htmx/user/_user_menu_destinations.html
  src/argus/htmx/templates/htmx/user/_user_menu_logout.html
  src/argus/htmx/templates/htmx/user/_user_menu_preferences.html
Labels: nonews

#1180 Redirect from root to incidents list
  changelog.d/+index-redirect.changed.md
  src/argus/htmx/urls.py
  src/argus/htmx/views.py
Labels: frontend

#1186 Update subdependencies
  requirements-django42.txt
  requirements-django50.txt
  requirements-django51.txt
  requirements.txt
Labels: dependencies, nonews

#1188 Add mention of djLint to README
  README.md
Labels: documentation, nonews

#1189 Cosmetic improvements to `MAINTAINING.rst`
  MAINTAINING.rst
Labels: documentation, nonews
