Repository Uninett/Argus, pull requests merged in 2025-01, with the labels that each got.

#1105 Skip towncrier check on 'nonews' label
  .github/workflows/towncrier.yml
Labels: nonews

#1106 Upgrade ruff version in pre-commit to 0.8.6
  .pre-commit-config.yaml
Labels: lint/reformat

#1107 Add rule to tox.ini to build sphinx docs
  tox.ini
Labels: nonews

#1098 Improve incidents file-path naming and template locations
  changelog.d/+singularize-incidents.changed.md
  docs/development/howtos/htmx-frontend/column_for_specific_tag.rst
  src/argus/htmx/constants.py
  src/argus/htmx/dateformat/views.py
  src/argus/htmx/defaults.py
  src/argus/htmx/incident/__init__.py
  src/argus/htmx/incident/constants.py
  src/argus/htmx/incident/customization.py
  src/argus/htmx/incident/filter.py
  src/argus/htmx/incident/forms.py
  src/argus/htmx/incident/urls.py
  src/argus/htmx/incident/utils.py
  src/argus/htmx/incident/views.py
  src/argus/htmx/templates/htmx/forms/badge_dropdown_select_multiple.html
  src/argus/htmx/templates/htmx/incident/_base.html
  src/argus/htmx/templates/htmx/incident/_base_incident_update_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_acknowledge_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_close_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_filterbox.html
  src/argus/htmx/templates/htmx/incident/_incident_list_menubar.html
  src/argus/htmx/templates/htmx/incident/_incident_list_refresh_info.html
  src/argus/htmx/templates/htmx/incident/_incident_list_update_menu.html
  src/argus/htmx/templates/htmx/incident/_incident_reopen_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_table.html
  src/argus/htmx/templates/htmx/incident/_incident_table_row.html
  src/argus/htmx/templates/htmx/incident/_incident_table_rows.html
  src/argus/htmx/templates/htmx/incident/_incident_ticket_autocreate_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_ticket_edit_modal.html
  src/argus/htmx/templates/htmx/incident/_incident_ticket_manual_create_modal.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_ack.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_actions.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_checkbox.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_combined_status.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_description.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_filterable_column_header.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_level.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_list_select_all_checkbox_header.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_pk.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_source.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_start_time.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_start_time_header.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_status.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_tag.html
  src/argus/htmx/templates/htmx/incident/cells/_incident_ticket.html
  src/argus/htmx/templates/htmx/incident/incident_detail.html
  src/argus/htmx/templates/htmx/incident/incident_list.html
  src/argus/htmx/templates/htmx/incident/responses/_incident_list_refresh.html
  src/argus/htmx/templates/htmx/incidents/_incident_combined_status.html
  src/argus/htmx/templates/htmx/incidents/_incident_list_update_menu.html
  src/argus/htmx/templates/htmx/incidents/_incident_ticket_autocreate_modal.html
  src/argus/htmx/themes/views.py
  src/argus/htmx/urls.py
  src/argus/htmx/user/views.py
  src/argus/htmx/widgets.py
  tests/htmx/incident/__init__.py
  tests/htmx/incident/test_utils.py
  tests/htmx/test_incident.py
Labels: frontend, refactor

#1112 Move towncrier part from `README` to docs
  README.md
  docs/development/howtos/changelog-entry.rst
  docs/development/howtos/release-checklist.rst
Labels: documentation, nonews

#1113 Set INTERNAL_IPS by default
  src/argus/site/settings/base.py
  src/argus/site/settings/dev.py
  src/argus/site/settings/prod.py
Labels: nonews, change setting

#977 Document how to toggle django-debug-toolbar with envvar
  changelog.d/+toggle-django-debug-toolbar.added.md
  docs/development/howtos/toggle-django-debug-toolbar.rst
Labels: documentation

#1117 Upgrade ruff in pre-commit to 0.9.1
  .pre-commit-config.yaml
  src/argus/auth/models.py
  src/argus/notificationprofile/admin.py
Labels: lint/reformat, nonews

#1081 Add vertical gap between elements in HTMX destinations page
  changelog.d/1080.added.md
  src/argus/htmx/templates/htmx/destination/_content.html
  src/argus/htmx/templates/htmx/destination/_form_list.html
Labels: blocked

#1072 Streamline defining and usage of preferences
  changelog.d/1072.changed.md
  docs/development/howtos/add-more-preferences.rst
  src/argus/auth/context_processors.py
  src/argus/auth/models.py
  src/argus/auth/utils.py
  src/argus/htmx/context_processors.py
  src/argus/htmx/dateformat/urls.py
  src/argus/htmx/dateformat/views.py
  src/argus/htmx/templates/htmx/base.html
  src/argus/htmx/templates/htmx/dateformat/_dateformat_dropdown.html
  src/argus/htmx/templates/htmx/dateformat/_dateformat_list.html
  src/argus/htmx/templates/htmx/page_size/_page_size_dropdown.html
  src/argus/htmx/templates/htmx/page_size/_page_size_list.html
  src/argus/htmx/templates/htmx/themes/_theme_dropdown.html
  src/argus/htmx/templates/htmx/themes/_theme_list.html
  src/argus/htmx/templates/htmx/user/_current_theme.html
  src/argus/htmx/templates/htmx/user/_dateformat_dropdown.html
  src/argus/htmx/templates/htmx/user/_page_size_dropdown.html
  src/argus/htmx/templates/htmx/user/_theme_dropdown.html
  src/argus/htmx/templates/htmx/user/preferences.html
  src/argus/htmx/themes/urls.py
  src/argus/htmx/themes/views.py
  src/argus/htmx/urls.py
  src/argus/htmx/user/preferences/models.py
  src/argus/htmx/user/urls.py
  src/argus/htmx/user/views.py
  tests/auth/models.py
  tests/auth/test_models.py
  tests/auth/test_utils.py
Labels: frontend, priority: high, performance

#1126 Add page title to destinations, timeslots and profiles pages
  src/argus/htmx/auth/views.py
  src/argus/htmx/destination/views.py
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/timeslot/views.py
Labels: polish, nonews

#1130 Make tailwind ignore admin templates
  src/argus/htmx/static/styles.css
  src/argus/htmx/tailwindtheme/tailwind.config.js
Labels: nonews

#1127 Fix create destination form generating extra div when submitting
  changelog.d/1129.fixed.md
  src/argus/htmx/templates/htmx/destination/_create_form.html
Labels: bug

#1142 Turn on overriding of django widget templates
  src/argus/htmx/appconfig.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/django/forms/div.html
Labels: frontend, nonews

#1118 Add dropdowns to profiles page
  src/argus/htmx/incident/filter.py
  src/argus/htmx/notificationprofile/urls.py
  src/argus/htmx/notificationprofile/views.py
  src/argus/htmx/templates/htmx/forms/checkbox_select_multiple.html
  src/argus/htmx/templates/htmx/forms/dropdown_select_multiple.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_buttons.html
  src/argus/htmx/templates/htmx/notificationprofile/_notificationprofile_form.html
  src/argus/htmx/templates/htmx/notificationprofile/notificationprofile_list.html
  src/argus/htmx/widgets.py
Labels: frontend, nonews

#1157 Move acknowledgement button to top of the feed
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx/incident/incident_detail.html
Labels: nonews
