Repository Uninett/Argus, pull requests merged in 2025-06, with the labels that each got.

#1480 Add CLI command to close incidents
  changelog.d/1450.added.md
  docs/development/management-commands.rst
  src/argus/dev/management/commands/close_incident.py
  src/argus/dev/utils.py
  tests/dev/test_close_incident.py
Labels: CLI

#1499 Make `SourceSystemType` factory use lowercase name
  changelog.d/1499.fixed.md
  src/argus/dev/management/commands/create_source.py
  src/argus/incident/factories.py
  tests/dev/test_create_source.py
Labels: bug, CLI

#1496 Remind to update user manual specifically in the PR template
  .github/pull_request_template.md
Labels: DevEx, nonews
