Repository Uninett/Argus, pull requests merged in 2025-05, with the labels that each got.

#1414 Add `source` argument to `create_fake_incident` CLI command
  changelog.d/+source_fake_incident.added.md
  docs/development/management-commands.rst
  src/argus/dev/management/commands/create_fake_incident.py
  src/argus/incident/models.py
  tests/dev/test_create_fake_incident.py
Labels: demo

#1417 Update glue service doc to mention API v2 instead of v1
  docs/integrations/glue-services/writing-glueservices.rst
Labels: documentation, nonews, Argus v2

#1410 Convert tables that may get really big to use bigint primary keys
  changelog.d/+bigintify.changed.md
  docs/reference/img/ER_model.png
  src/argus/incident/migrations/0009_use_bigautofield_on_quickly_growing_tables.py
  src/argus/incident/models.py
Labels: data model, Argus v2

#1418 Update PR template to not mention API v1
  .github/pull_request_template.md
Labels: nonews

#1422 Remove mentions of the old frontend and dataporten from README
  README.md
Labels: documentation, nonews

#1405 Use hatchling+versioningit for packaging
  MANIFEST.in
  pyproject.toml
Labels: cleanup, nonews, packaging

#1407 Squash migrations
  changelog.d/+squash-migrations.changed.md
  src/argus/auth/migrations/0001_initial.py
  src/argus/auth/migrations/0002_squashed_auth_20250512_add_preferences_model.py
  src/argus/htmx/migrations/0001_initial.py
  src/argus/incident/migrations/0001_squashed_incident_20250514.py
  src/argus/notificationprofile/migrations/0001_squashed_notificationprofile_20250512.py
  tests/migration_example.py
Labels: data model, refactor, cleanup

#1423 Hide all spa stuff
  constraints.txt
  docs/django_settings.py
  docs/reference/htmx-frontend.rst
  pyproject.toml
  requirements-django52.txt
  requirements.txt
  src/argus/auth/drftoken/__init__.py
  src/argus/auth/drftoken/serializers.py
  src/argus/auth/drftoken/urls.py
  src/argus/auth/drftoken/views.py
  src/argus/auth/urls.py
  src/argus/site/api_v1_urls.py
  src/argus/site/api_v2_urls.py
  src/argus/site/settings/dev.py
  src/argus/site/settings/test_CI.py
  tox.ini
Labels: nonews, Argus v2

#1427 Remove spa-specific settings from docs
  docs/reference/site-specific-settings.rst
Labels: documentation, nonews, Argus v2

#1445 Drop remainder of mentions of API v1 and SPA
  docs/reference/api/v2.rst
  src/argus/base/templates/index.html
  src/argus/dev/utils.py
  src/argus/htmx/utils.py
  src/argus/incident/views.py
  src/argus/spa/ws/models.py
  src/argus/util/signals.py
  tests/V1/dev/__init__.py
  tests/V1/dev/test_utils.py
  tests/incident/test_serializers.py
  tests/incident/ticket_plugins/test_dummy.py
Labels: nonews, Argus v2

#1449 Add CLI command for user management
  changelog.d/+createuser-command.added.md
  docs/development/management-commands.rst
  src/argus/auth/management/commands/changeuser.py
  src/argus/auth/management/commands/createuser.py
  tests/auth/management_commands/__init__.py
  tests/auth/management_commands/test_changeuser.py
  tests/auth/management_commands/test_createuser.py
Labels: CLI, demo

#1458 Update user manual
  docs/index.rst
  docs/user-manual.rst
Labels: documentation, Argus v2

#1446 Actually delete API version v1 and its tests and docs for old frontend
  changelog.d/+delete-v1.removed.md
  docs/reference/api/v1.rst
  docs/reference/react-frontend.rst
  src/argus/auth/V1/__init__.py
  src/argus/auth/V1/serializers.py
  src/argus/auth/V1/urls.py
  src/argus/auth/V1/views.py
  src/argus/filter/V1/__init__.py
  src/argus/filter/V1/constants.py
  src/argus/filter/V1/serializers.py
  src/argus/filter/V1/validators.py
  src/argus/incident/V1/__init__.py
  src/argus/incident/V1/serializers.py
  src/argus/incident/V1/urls.py
  src/argus/incident/V1/views.py
  src/argus/notificationprofile/V1/__init__.py
  src/argus/notificationprofile/V1/serializers.py
  src/argus/notificationprofile/V1/urls.py
  src/argus/notificationprofile/V1/views.py
  src/argus/site/api_v1_urls.py
  src/argus/spa/__init__.py
  src/argus/spa/apps.py
  src/argus/spa/dataporten/__init__.py
  src/argus/spa/dataporten/social.py
  src/argus/spa/root_urls.py
  src/argus/spa/settings.py
  src/argus/spa/spa_settings.py
  src/argus/spa/spa_urls.py
  src/argus/spa/urls.py
  src/argus/spa/utils.py
  src/argus/spa/views.py
  src/argus/spa/ws/__init__.py
  src/argus/spa/ws/asgi.py
  src/argus/spa/ws/consumers.py
  src/argus/spa/ws/models.py
  tests/V1/__init__.py
  tests/V1/auth/__init__.py
  tests/V1/auth/test_auth.py
  tests/V1/auth/test_spa_views.py
  tests/V1/auth/test_views.py
  tests/V1/incident/__init__.py
  tests/V1/incident/test_event.py
  tests/V1/incident/test_source_system.py
  tests/V1/incident/test_views.py
  tests/V1/notificationprofile/__init__.py
  tests/V1/notificationprofile/test_views.py
  tests/V1/spa/__init__.py
  tests/V1/spa/test_utils.py
  tests/V1/spa/test_views.py
  tests/V1/v1_root_urls.py
Labels: documentation, tests, Argus v2

#1428 Remove old frontend from "about argus" doc
  docs/about-argus.rst
Labels: nonews

#1481 Add demo banner
  changelog.d/1164.added.md
  docs/reference/site-specific-settings.rst
  src/argus/htmx/appconfig.py
  src/argus/htmx/context_processors.py
  src/argus/htmx/static/styles.css
  src/argus/htmx/templates/htmx_base.html
  src/argus/site/settings/base.py
Labels: frontend, demo

#1485 Upgrade all dependencies
  requirements-django52.txt
  requirements.txt
Labels: dependencies

#1486 Add option to set source type for fake incidents
  changelog.d/+source-type-create-fake-incident.added.md
  src/argus/dev/management/commands/create_fake_incident.py
  tests/dev/test_create_fake_incident.py
Labels: CLI
