Repository Uninett/Argus, pull requests merged in 2025-08, with the labels that each got.

#1522 Update contributors
  CONTRIBUTORS.md
  changelog.d/+update-contributors.changed.md
  docs/development/howtos/update-contributors.rst
Labels: documentation

#1483 Merge argus.htmx settings with default settings
  changelog.d/+merge-settings.changed.md
  docs/development/howtos/change-settings.rst
  docs/reference/htmx-frontend.rst
  pyproject.toml
  src/argus/htmx/settings.py
  src/argus/site/settings/backend.py
  src/argus/site/settings/base.py
  src/argus/site/settings/dev.py
  src/argus/site/settings/prod.py
  src/argus/site/settings/test_CI.py
  tox.ini
Labels: rc-future, change setting, Argus v2, needs NOTES

#1525 Add tool-specific howtos
  CONTRIBUTING.rst
  changelog.d/+add-tool-specific-howtos.added.md
  docs/development/howtos/howtos-for-git.rst
  docs/development/howtos/howtos-for-github.rst
  docs/development/howtos/update-contributors.rst
Labels: documentation, DevEx

#1524 Add script to run the same standalone tailwind extra version
  src/argus/htmx/tailwindtheme/__init__.py
  src/argus/htmx/tailwindtheme/config.py
  src/argus/htmx/tailwindtheme/get_tailwind.py
  src/argus/htmx/tailwindtheme/utils.py
Labels: frontend, DevEx, nonews
